{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemUnexpected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/swiftparsec\/errormessage\/systemunexpected(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/SwiftParsec\/documentation\/SwiftParsec\/ErrorMessage\/systemUnexpected(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"SystemUnexpected"},{"type":"text","text":" message is automatically generated by the"},{"type":"text","text":" "},{"type":"codeVoice","code":"satisfy"},{"type":"text","text":" combinator. The argument is the unexpected input."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemUnexpected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"ErrorMessage.systemUnexpected(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:11SwiftParsec12ErrorMessageO16systemUnexpectedyACSScACmF","modules":[{"name":"SwiftParsec"}]},"hierarchy":{"paths":[["doc:\/\/SwiftParsec\/documentation\/SwiftParsec","doc:\/\/SwiftParsec\/documentation\/SwiftParsec\/ErrorMessage"]]},"references":{"doc://SwiftParsec/documentation/SwiftParsec/ErrorMessage/systemUnexpected(_:)":{"role":"symbol","title":"ErrorMessage.systemUnexpected(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemUnexpected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"SystemUnexpected"},{"type":"text","text":" message is automatically generated by the"},{"type":"text","text":" "},{"type":"codeVoice","code":"satisfy"},{"type":"text","text":" combinator. The argument is the unexpected input."}],"identifier":"doc:\/\/SwiftParsec\/documentation\/SwiftParsec\/ErrorMessage\/systemUnexpected(_:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftparsec\/errormessage\/systemunexpected(_:)"},"doc://SwiftParsec/documentation/SwiftParsec":{"role":"collection","title":"SwiftParsec","abstract":[{"type":"text","text":"Unleash the Power of Parser Combinators in Swift!"}],"identifier":"doc:\/\/SwiftParsec\/documentation\/SwiftParsec","kind":"symbol","type":"topic","url":"\/documentation\/swiftparsec"},"doc://SwiftParsec/documentation/SwiftParsec/ErrorMessage":{"role":"symbol","title":"ErrorMessage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessage"}],"abstract":[{"type":"text","text":"Message represents parse error messages. The fine distinction between"},{"type":"text","text":" "},{"type":"text","text":"different kinds of parse errors allows the system to generate quite good"},{"type":"text","text":" "},{"type":"text","text":"error messages for the user. It also allows error messages that are"},{"type":"text","text":" "},{"type":"text","text":"formatted in different languages. Each kind of message is generated by"},{"type":"text","text":" "},{"type":"text","text":"different combinators."}],"identifier":"doc:\/\/SwiftParsec\/documentation\/SwiftParsec\/ErrorMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessage"}],"url":"\/documentation\/swiftparsec\/errormessage"}}}